from __future__ import unicode_literals
from django.db import models
from datetime import date, timezone
from django.core.files.storage import FileSystemStorage

class submittal(models.Model):
    submitted = models.DateField(blank=True)
    urgency = models.CharField(max_length=25, null=True, blank=True, default='normal')
    title = models.CharField(max_length=150, null=True, default=' ')
    annum = models.CharField(max_length=6, null=True, blank= True, default=' ')
    lname = models.CharField(max_length=50,  null=True, default=' ')
    fname = models.CharField(max_length=50,  null=True, default=' ')
    affiliation = models.CharField(max_length=100, null=True, default=' ')
    contact  = models.CharField(max_length=100, null=True, blank=True, default=' ')   
    startdate = models.DateField(null=True, blank=True)
    enddate = models.DateField(null=True, blank=True)
    justification = models.CharField(max_length=1000, null=True, blank = True, default='')
    instructions = models.CharField(max_length=2000, null=True, default=' ')
    notes = models.CharField(max_length=1000, blank=True, null=True, default=' ')
    feedback = models.CharField(max_length=1000, null=True, blank=True, default=' ')
    graphic = models.FileField(null=True)
    TS = models.BooleanField( null=True, blank=True)
    HR = models.BooleanField(null=True, blank=True)
    NI = models.BooleanField( null=True, blank=True)
    WK = models.BooleanField(null=True, blank=True)
    MO = models.BooleanField( null=True, blank=True) 
    CT = models.BooleanField( null=True, blank=True)
    EB = models.BooleanField(null=True, blank=True)
    XP = models.BooleanField( null=True, blank=True)
    HE = models.BooleanField(null=True, blank=True)
    LV = models.BooleanField( null=True, blank=True)
    SP = models.BooleanField(null=True, blank=True)
    SO = models.BooleanField( null=True, blank=True)
    spectroscopy = models.CharField(max_length=50, null=True, blank=True, default=' ')
    wavelengths = models.CharField(max_length=25, null=True, blank=True, default='N/A')
    Vp = models.BooleanField(null=True, blank=True)
    Cp = models.BooleanField(null=True, blank=True)
    Dp = models.BooleanField(null=True, blank=True)
    Pp = models.BooleanField(null=True, blank=True)
    U = models.BooleanField( null=True, blank=True)
    B = models.BooleanField(null=True, blank=True)
    V = models.BooleanField( null=True, blank=True)
    R = models.BooleanField(null=True, blank=True)
    I = models.BooleanField( null=True, blank=True)
    uu = models.BooleanField(null=True, blank=True)
    g = models.BooleanField( null=True, blank=True)
    rr = models.BooleanField(null=True, blank=True)
    l = models.BooleanField( null=True, blank=True)
    z = models.BooleanField(null=True, blank=True)
    cv = models.BooleanField( null=True, blank=True)
    cr = models.BooleanField(null=True, blank=True)
    s1 = models.CharField(max_length=400,blank = True, null=True, default=' ')
    s2 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s3 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s4 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s5 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s6 = models.CharField(max_length=150,blank = True,null=True,  default=' ')
    s7 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s8 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s9 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s10 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s11 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s12 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s13 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s14 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s15 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s16 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s17 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s18 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s19 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s20 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s21 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s22 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s23 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s24 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    s25 = models.CharField(max_length=150,blank = True, null=True, default=' ')
    status = models.CharField(max_length=50, null=True, blank=True, default='pending ')
    priority= models.CharField(max_length=50, null=True, blank=True, default=' ')
    approved =  models.DateField(null=True,blank=True)




