# Generated by Django 4.0.3 on 2022-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='graphic',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
