# Generated by Django 4.0.3 on 2022-04-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_submittal_graphic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittal',
            old_name='graphic',
            new_name='table',
        ),
    ]
