# Generated by Django 4.0.3 on 2022-04-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_rename_graphic_submittal_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='table',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
