# Generated by Django 4.0.3 on 2022-04-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_submittal_forums_alter_submittal_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='table',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
